# Default values for adoagent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

configMap:
  AZP_URL: ""
  AZP_POOL: Default
  AZP_AGENT_NAME: helm-ado-agent-01

secret:
  AZP_TOKEN: ""
  